Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/manufacturers', to: 'manufacturers#index'
  get '/manufacturers/new', to: 'manufacturers#new'
  get '/manufacturers/:id/edit', to: 'manufacturers#edit'
  patch '/manufacturers/:id', to: 'manufacturers#update'
  post '/manufacturers', to: 'manufacturers#create'
  get '/manufacturers/:id', to: 'manufacturers#show'
  get '/manufacturers/:id/bicycles', to: 'manufacturers#bicycles'
  get '/manufacturers/:id/bicycles/new', to: 'bicycles#new'
  post '/manufacturers/:id/bicycles', to: 'bicycles#create'
  delete '/manufacturers/:id', to: 'manufacturers#destroy'
  delete '/manufacturers', to: 'manufacturers#destroy'
  get '/bicycles/', to: 'bicycles#index'
  get '/bicycles/:id', to: 'bicycles#show'
  get '/bicycles/:id/edit', to: 'bicycles#edit'
  patch '/bicycles/:id', to: 'bicycles#update'
  delete '/bicycles/:id', to: 'bicycles#destroy'
  delete '/bicycles', to: 'bicycles#destroy'


  get '/authors', to: 'authors#index'
  get '/authors/new', to: 'authors#new'
  get '/authors/:id/edit', to: 'authors#edit'
  patch '/authors/:id', to: 'authors#update'
  post '/authors', to: 'authors#create'
  get '/authors/:id/book_listing/new', to: 'books#new'
  post '/authors/:id/book_listing', to: 'books#create'
  delete '/authors/:id', to: 'authors#destroy'
  get '/authors/:id', to: 'authors#show'
  get '/books', to: 'books#index'
  get '/books/:id', to: 'books#show'
  get '/authors/:id/book_listing', to: 'authors#book_listing'
  get '/books/:id/edit', to: 'books#edit'
  patch '/books/:id', to: 'books#update'
  patch '/authors/:id', to: 'authors#update'
  delete '/books/:id', to: 'books#destroy'

end
